### PR TITLE
lexer: better handling of character and byte literals

### LINKED ISSUE #1003: reporting: wrap newlines correctly in reporting view
Currently, if an error message within span labels contains newline (`\n`) character, the reporting doesn't appropriately wrap them 
around and just prints the label as a raw. For example:
```rs
error: non-ascii character in byte literal
  --> ~/examples/main.hash:78:3
77 |   b'👍',
78 |   b'😘'
   |     ^ must be ASCII
this multibyte character does not fit into a single byte
```
The second line `"this multibyte ..."` is put onto the next line without properly incorporating it into the reporting view.  

This should be fixed by checking if the span label has multiple lines of content, and appropriately formatting it to be aligned with 
the rest of the text.

### PR DESCRIPTION
**Pull request by feds01**
This PR deals with several issues arising from Unicode handling in the compiler. Firstly, the compiler would completely bork when it encountered combining marks. Column offsets and reporting rendering were completely incorrect, and the lexer error message was somewhat confusing. So, this PR does the following:

- lexer: emit error for non-ASCII byte literals
- source: correctly compute column offsets (accounting for Unicode)
- reporting: account for combining marks when drawing span annotations
- lexer: improve errors for combining marks in byte and character literals
- fix #1003

### CODE REVIEW

File: compiler/hash-reporting/src/render.rs [hunk 1]
```diff
@@ -111,6 +111,118 @@ impl ReportCodeBlock {
...
+
+            // If it is a combining mark, its not going to be rendered within the
+            // span, so we need to subtract it from the total width.
+            if unicode_normalization::char::is_combining_mark(ch) {
+                combining_marks += 1;
+            }
+        }
+
+        (end - start).saturating_sub(combining_marks)
+    }
```
Comment (kontheocharis) [inline compiler/hash-reporting/src/render.rs:174]: Interesting approach. Instead of the `unicode_normalization` crate, `unicode_segmentation` could be used which offers a `.graphemes()` iterator so that this function could be replaced by `.graphemes().count()`. Not necessary though, just a potential simplification.

File: compiler/hash-reporting/src/report.rs [hunk 2]
```diff
@@ -151,6 +151,13 @@ pub macro help {
     }
 }
 
+/// Create a `note` note with the given message.
+pub macro note {
```
Comment (kontheocharis) [inline compiler/hash-reporting/src/report.rs:155]: Why are we using first-class macros in this crate?

**Review by kontheocharis — APPROVED** [review]

File: compiler/hash-reporting/src/render.rs (hunk 1 above)
Comment (feds01) [reply compiler/hash-reporting/src/render.rs:174]: There is also the `unicode-width` crate, which should compute the true column width of a given Unicode string. Perhaps it is worth leaving a todo/investigate note?

File: compiler/hash-reporting/src/report.rs (hunk 2 above)
Comment (feds01) [reply compiler/hash-reporting/src/report.rs:155]: I guess it just started as a trend, and now it continues

Comment (kontheocharis) [reply compiler/hash-reporting/src/report.rs:155]: I guess so

**Review by kontheocharis — APPROVED** [review]
